services:
  - type: web
    name: property-management-api
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1
